# fly.toml app configuration file generated for {flc-heros-et-dragon} on 2023-08-22T19:33:23+02:00
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
# Replace {app_name} with the name of your app and it may work out of the box.

app = "{flc-heros-et-dragon}"
primary_region = "ams"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

[deploy]
release_command = "/app/bin/migrate"

[env]
PHX_HOST = "{flc-heros-et-dragon}.fly.dev"
PORT = "8080"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
[http_service.concurrency]
type = "connections"
hard_limit = 1000
soft_limit = 1000
