# fly.toml app configuration file generated for forbiddenlands on 2023-05-16T09:47:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "forbiddenlands"
primary_region = "fra"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "forbiddenlands.fly.dev"
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  min_machines_running = 0
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
